workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1  # 指定构建实例
    environment:
      flutter: stable
      xcode: 16.0
      cocoapods: default
      ios_signing:  # 添加自动签名配置
        distribution_type: ad_hoc  # 或 app_store
        bundle_identifier: com.chongloutech.lehui
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: iOS Pod install
        script: |
          cd ios
          pod install --repo-update
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign  # 改为 release
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
